name: eliza_chat
description: A Dart version of the classic Eliza chatbot.
version: 1.0.0
repository: https://github.com/thpir/eliza_chat

environment:
  sdk: ^3.2.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
